### ISSUE TITLE
This looks like exactly what I'm looking for

### ISSUE THREAD

**Issue by didlie** [sammacbeth/pluggable-discovery-swarm#1]
I'm building a p2p network topography with an evolving set of static URL nodes, each providing the signaling services to specific sets of requests client nodes, ... and maintaining a hyperledger accross the URL - network.

Is this a concept that can be implemented with this repo?

**Comment by sammacbeth** [comment]
This repo was an experiment on extracting aspects of the `discovery-swarm` module, plus others into components. I'm not currently using or maintaining this. You may want to look at [libp2p](https://libp2p.io/), [hyperswarm](https://github.com/hyperswarm), or the [Signalhub ecosystem](https://github.com/SignalHub-Ecosystem).
